name:                text1
version:             0.1.0.0
github:              tmortiboy/text1
license:             MIT
author:              Tom Mortiboy
maintainer:          Tom Mortiboy
copyright:           2020 seek-oss, 2020 text1 contributors

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/seek-oss/text1#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- amazonka-core
- attoparsec
- case-insensitive
- cassava
- deepseq
- hashable
- lens
- positive
- QuickCheck
- quickcheck-instances
- scientific
- servant
- text
- these
- uuid-types

library:
  source-dirs: src

tests:
  text1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text1
    - generic-arbitrary
    - hspec
    - unordered-containers
